sudo: required
services: docker
language: generic

script:
    - curl -O https://raw.githubusercontent.com/cyber-dojo/ruby/master/push.sh
    - chmod +x push.sh
    - ./pipe_build_up_test.sh
    - ./push.sh
