
version: '2.2'

services:

  storer:
    container_name: cyber-dojo-storer
    cpu_shares: 1024
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure
    ports:
      - ${CYBER_DOJO_STORER_SERVER_PORT}:${CYBER_DOJO_STORER_SERVER_PORT}
    volumes_from:
      - container:${CYBER_DOJO_KATA_DATA_CONTAINER_NAME}:rw
