
version: '2.2'

services:

  storer_client:
    user: nobody
    image: cyberdojo/storer_client
    init: true
    container_name: test_storer_client
    read_only: true
    tmpfs: /tmp
    build:
      context: client
      args:
        - PORT=${CYBER_DOJO_STORER_CLIENT_PORT}
    environment:
      - CYBER_DOJO_KATAS_ROOT
    ports:
      - ${CYBER_DOJO_STORER_CLIENT_PORT}:${CYBER_DOJO_STORER_CLIENT_PORT}

  # - - - - - - - - - - - - - - - - - - -

  storer:
    user: storer
    image: cyberdojo/storer
    init: true
    read_only: true
    tmpfs: /tmp
    build:
      context: server
      args:
        - PORT=${CYBER_DOJO_STORER_SERVER_PORT}
    environment:
      - CYBER_DOJO_KATAS_ROOT
