
version: '2.2'

services:

  storer_client:
    build:
      context: client
      args:
        - CYBER_DOJO_STORER_HOME=${CYBER_DOJO_STORER_HOME}
        - PORT=${CYBER_DOJO_STORER_CLIENT_PORT}
    user: nobody
    image: cyberdojo/storer_client
    init: true
    container_name: test_storer_client
    read_only: true
    tmpfs: /tmp
    depends_on:
      - storer
    restart: 'no'
    environment:
      - CYBER_DOJO_STORER_SERVICE_NAME
      - CYBER_DOJO_STORER_SERVICE_PORT
      - CYBER_DOJO_KATAS_ROOT
      - CYBER_DOJO_COVERAGE_ROOT
    ports:
      - ${CYBER_DOJO_STORER_CLIENT_PORT}:${CYBER_DOJO_STORER_CLIENT_PORT}

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  storer:
    container_name: test_storer_server
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
    restart: 'no'

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # starter is handy in tests for creating kata-manifests

  starter:
    user: nobody
    image: cyberdojo/starter
    init: true
    container_name: test_storer_starter_server
    read_only: true
    tmpfs: /tmp
    environment:
      - CYBER_DOJO_START_POINTS_ROOT
    volumes:
      - ./server/test/start_points:${CYBER_DOJO_START_POINTS_ROOT}:ro
