
version: '2.2'

services:

  storer_client:
    environment:
      - CYBER_DOJO_COVERAGE_ROOT

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  storer_server:
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
    volumes:
      - ./server/old_kata_manifest_volume/42/0BD5D5BE/manifest.json:${CYBER_DOJO_KATAS_ROOT}/42/0BD5D5BE/manifest.json:ro

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  starter_server:
    user: nobody
    image: cyberdojo/starter
    init: true
    container_name: storer_test_starter_server
    read_only: true
    tmpfs: /tmp
    environment:
      - CYBER_DOJO_START_POINTS_ROOT
    volumes:
      - ./server/start_points:${CYBER_DOJO_START_POINTS_ROOT}:ro


