
version: '2.2'

services:

  storer_client:
    user: nobody
    image: cyberdojo/storer_client
    init: true
    container_name: storer_client
    build:
      context: client
      args:
        - PORT=${CYBER_DOJO_STORER_CLIENT_PORT}
    ports:
      - ${CYBER_DOJO_STORER_CLIENT_PORT}:${CYBER_DOJO_STORER_CLIENT_PORT}


  storer:
    user: cyber-dojo
    image: cyberdojo/storer
    init: true
    container_name: storer_server
    read_only: true
    tmpfs: /tmp
    build:
      context: server
      args:
        - PORT=${CYBER_DOJO_STORER_SERVER_PORT}
    environment:
      - CYBER_DOJO_KATAS_ROOT
    volumes_from:
      - container:${CYBER_DOJO_GIT_KATA_DATA_CONTAINER}:rw
