
version: '2.2'

services:

  storer_client:
    user: nobody
    image: cyberdojo/storer_client
    init: true
    container_name: test_storer_client
    read_only: true
    tmpfs: /tmp
    build:
      context: client
      args:
        - PORT=${CYBER_DOJO_STORER_CLIENT_PORT}
    environment:
      - CYBER_DOJO_KATAS_ROOT
    ports:
      - ${CYBER_DOJO_STORER_CLIENT_PORT}:${CYBER_DOJO_STORER_CLIENT_PORT}


  storer_server:
    user: cyber-dojo
    image: cyberdojo/storer
    init: true
    container_name: test_storer_server
    read_only: true
    tmpfs: /tmp
    build:
      context: server
      args:
        - PORT=${CYBER_DOJO_STORER_SERVER_PORT}
    environment:
      - CYBER_DOJO_KATAS_ROOT
    volumes_from:
      - container:${CYBER_DOJO_KATA_DATA_CONTAINER_NAME}:rw
