
version: '2.2'

services:

  storer_client:
    build:
      context: client
    user: nobody
    image: cyberdojo/storer-client
    init: true
    container_name: test-storer-client
    tmpfs: /tmp
    depends_on:
      - storer
    restart: 'no'

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  storer:
    container_name: test-storer-server
    ports:
      - 4577:4577
    restart: 'no'

  # - - - - - - - - - - - - - - - - - - - - - - -
  # monitoring

  prometheus:
    container_name: test-storer-prometheus

  grafana:
    container_name: test-storer-grafana
    ports:
      - '3001:3001'

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # starter is handy in tests for creating kata-manifests

  starter:
    user: nobody
    image: cyberdojo/starter
    init: true
    container_name: test-storer-starter-server
    expose: [ "4527" ]
    read_only: true
    tmpfs: /tmp
    environment:
      - STARTER_SERVICE_PORT=4527
      - START_POINTS_ROOT
    volumes:
      - ./start_points:${START_POINTS_ROOT}:ro
