
version: '2.2'

services:

  storer_client:
    environment:
      - CYBER_DOJO_COVERAGE_ROOT

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  storer:
    environment:
      - CYBER_DOJO_COVERAGE_ROOT

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # starter is handy in tests for creating kata-manifests

  starter:
    user: nobody
    image: cyberdojo/starter
    init: true
    container_name: storer_test_starter_server
    read_only: true
    tmpfs: /tmp
    environment:
      - CYBER_DOJO_START_POINTS_ROOT
    volumes:
      - ./server/test/start_points:${CYBER_DOJO_START_POINTS_ROOT}:ro
