
version: '2.2'

volumes:
  # monitoring
  grafana_data: {}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

services:

  storer:
    build:
      context: .
      args:
        - SHA
    user: storer
    image: cyberdojo/storer
    init: true
    tmpfs: /tmp
