
version: '2.2'

volumes:
  # monitoring
  grafana_data: {}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

services:

  storer:
    build:
      context: server
      args:
        - ALPINE_VERSION=${ALPINE_VERSION}
        - CYBER_DOJO_HOME=${CYBER_DOJO_HOME}
        - SHA=${SHA}
    user: storer
    image: cyberdojo/storer
    expose: [ "${STORER_SERVICE_PORT}" ]
    init: true
    read_only: true
    tmpfs: /tmp
    environment:
      - CYBER_DOJO_KATAS_ROOT
      - STORER_SERVICE_PORT
    depends_on:
      - prometheus

  # - - - - - - - - - - - - - - - - - - - - - - -
  # monitoring

  prometheus:
    image: cyberdojo/prometheus
    init: true
    cpu_shares: 128

  grafana:
    image: cyberdojo/grafana
    init: true
    cpu_shares: 128
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    env_file:
      - ./grafana.env
