
version: '2'

services:
  storer_client:
    user: nobody
    image: cyberdojo/storer_client
    build:
      context: client
      args: [ PORT=4578 ]
    ports: [ "4578:4578" ]
    container_name: storer_client

  storer:
    user: root
    image: cyberdojo/storer
    build:
      context: server
      args: [ PORT=4577 ]
    container_name: storer_server
    environment: [ CYBER_DOJO_KATAS_ROOT=/tmp/katas ]
    volumes_from:
      - container:cyber-dojo-git-kata-DATA-CONTAINER:rw
    read_only: true
    tmpfs: /tmp
