
version: '2.2'

services:

  storer_client:
    environment:
      - CYBER_DOJO_COVERAGE_ROOT

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  storer:
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
    volumes:
      # language:Python-py.test
      - ./server/old_katas_manifest_volume/42/0BD5D5BE/manifest.json:${CYBER_DOJO_KATAS_ROOT}/42/0BD5D5BE/manifest.json:ro
      # language:Ruby-Rspec
      - ./server/old_katas_manifest_volume/42/1AFD7EC5/manifest.json:${CYBER_DOJO_KATAS_ROOT}/42/1AFD7EC5/manifest.json:ro
      # language:C
      - ./server/old_katas_manifest_volume/42/1F303E80/manifest.json:${CYBER_DOJO_KATAS_ROOT}/42/1F303E80/manifest.json:ro

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  starter:
    user: nobody
    image: cyberdojo/starter
    init: true
    container_name: storer_test_starter_server
    read_only: true
    tmpfs: /tmp
    environment:
      - CYBER_DOJO_START_POINTS_ROOT
    volumes:
      - ./server/start_points:${CYBER_DOJO_START_POINTS_ROOT}/languages:ro


