
version: '2.2'

volumes:
  # monitoring
  grafana_data: {}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

services:

  storer:
    build:
      context: server
      args:
        - ALPINE_VERSION=3.7
        - STORER_HOME=/app
        - SHA
    user: storer
    image: cyberdojo/storer
    init: true
    read_only: true
    tmpfs: /tmp
    environment:
      - CYBER_DOJO_KATAS_ROOT
    depends_on:
      - prometheus

  # - - - - - - - - - - - - - - - - - - - - - - -
  # monitoring

  prometheus:
    image: cyberdojo/prometheus
    init: true
    cpu_shares: 128

  grafana:
    image: cyberdojo/grafana
    init: true
    cpu_shares: 128
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    env_file:
      - ./grafana.env
