
version: '2.2'

services:

  storer_client:
    environment:
      - CYBER_DOJO_COVERAGE_ROOT

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  storer:
    environment:
      - CYBER_DOJO_COVERAGE_ROOT

