
version: '2.2'

services:

  storer:
    container_name: cyber-dojo-storer
    cpu_shares: 1024
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure
    read_only: true
    volumes_from:
      - container:${CYBER_DOJO_KATA_DATA_CONTAINER_NAME}:rw

  # - - - - - - - - - - - - - - - - - - - - - - -
  # monitoring

  prometheus:
    container_name: cyber-dojo-prometheus

  grafana:
    container_name: cyber-dojo-grafana
    ports:
      - '3000:3000'
